### ISSUE TITLE
Is it possible to set `[appendix]` attribute to an annex section?

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/tex2mn#102]
*From https://github.com/metanorma/mn-samples-tex-iso/issues/5*
*This issue is related with https://github.com/metanorma/tex2mn/issues/98*

Is it possible to set `[appendix]` attribute to an annex section (including its obligation)?

For example:
````
[appendix,obligation=informative]
== Annex title
...
````

**Comment by paolobrasolin** [comment]
The example here shows how: https://github.com/metanorma/tex2mn/blob/master/test/test_appendix.rb#L91

Here is the related documentation:
* https://github.com/metanorma/tex2mn/blob/master/manual/sections.adoc#appendices
* https://github.com/metanorma/tex2mn/blob/master/manual/sections.adoc#obligations

The `\mn` macro is not documented as an independent entity, but it's used in various situations to provide extra attributes to the "nearest thing".

**Comment by manuelfuenmayor** [comment]
Thanks @paolobrasolin! This approach looks good to me.

Now, after the `\appendix` macro is called, is there a way to return to normal section approach? (To be honest, I haven't found any case where this would be needed since the appendix sections are always the last ones apparently, but I ask for curiosity :smile:.)
