### ISSUE TITLE
Add Windows testing via GitHub Actions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/tex2mn#44]
Refer to the `windows.yml` file from https://github.com/metanorma/metanorma-iec/pull/10/files .

**Comment by paolobrasolin** [comment]
@ronaldtse I cleaned up GHA configurations for `ubuntu`, `macos` and `windows` workflows.

I managed to get `ubuntu` and `macos` working fine, but `windows` is a bit beyond me.

I'm stumped on indirect dependencies of `LaTeXML` (i.e. dev libraries to link during the build).

I think I pinpointed at least one of the missing dependencies (Berkley DB): https://github.com/metanorma/tex2mn/commit/5ed5d2fb7f58ca178705134384d1171fbb543754#diff-222da3d5159ccbea64c56d21b445f986R24

I'm unsure how to approach its programmatic installation, though.

Is there anybody on team who is well-versed in windows and can lend a hand? The pending PR is #63

**Comment by ronaldtse** [comment]
@paolobrasolin LaTeXML can be installed via Chocolatey (https://chocolatey.org/packages/latexml, https://github.com/metanorma/chocolatey-latexml). @CAMOBAP795 did the packaging and he can help you with setting it up on Windows GHA.

**Comment by paolobrasolin** [comment]
Thanks @ronaldtse. Yes, I noticed that Chocolatey package, but the problem here is that we need to install LaTeXML from the GH repo, at a specific commit (git://github.com/brucemiller/LaTeXML.git@9a0e7dc5). Is that possible with Chocolatey, @CAMOBAP795 ?

**Comment by paolobrasolin** [comment]
Got it! Thanks @ronaldtse, @CAMOBAP795 work nudged me in the right direction.

For the record, I'm using @shogo82148's `actions-setup-perl` to set up Perl on all three OSs.
However one needs to explicitly put Strawberry Perl before the preinstalled MSYS Perl to override it, see https://github.com/metanorma/tex2mn/commit/6cd3a580da053adb400ea888dd782e64c66df3de#diff-222da3d5159ccbea64c56d21b445f986R30

The rest is pretty much trivial.

**Comment by ronaldtse** [comment]
Awesome. I'd propose that we make an `actions-setup-latexml` to setup LaTeXML too...

**Comment by ronaldtse** [comment]
And `action-setup-mn`... https://github.com/metanorma/action-setup-mn/issues/1 which was already created some time ago..
