### ISSUE TITLE
Integrate tex2mn into MN

### ISSUE THREAD

**Issue by paolobrasolin** [metanorma/tex2mn#96]
I submitted the package to CTAN and set up a GHA action to release new tags on both GH and CTAN automatically.

---

In essence, `tex2mn` is composed of

* `metanorma.cls` which is a LaTeX class to directly compile standard documents from `tex` to `pdf`. We don't *strictly* need it for MN, but it's nice for the user to have.
* `metanorma.cls.ltxml` which is a `latexml` script which allows transpiling `tex` to an intermediate `xml` representation
* `metanorma.xsl` which is a `latexmlpost` stylesheet which allows transpiling the intermediate `xml` representation to Metanorma's `adoc`

Running `tex2mn` is a two step job:

```bash
latexml input.tex  --destination=intermediate.xml --preload=metanorma.cls --nocomments --strict
latexmlpost intermediate.xml --destination=output.adoc --stylesheet=metanorma.xsl --nocrossref --nodefaultresources
# NOTE: latexml is actually prealoading metanorma.cls.ltxml, which is in the same folder as metanorma.cls
```

In case the workflow benefits from it, these commands also work piping `stdin`/`stdout`:

```bash
cat input.tex \
  | latexml - --preload=metanorma.cls --nocomments --strict \
  | latexmlpost - --stylesheet=metanorma.xsl --nocrossref --nodefaultresources |
  > output.adoc
```

All the flags are needed as they are because of technical reasons (not delving into that here).

The exceptions are:
* `--preload=metanorma.cls`: if `tex2mn` (i.e. the `metanorma` CTAN package) is installed correctly, this flag can be omitted, as `latexml` can automatically solve the dependency
* `--stylesheet=metanorma.xsl`: even if `tex2mn` (i.e. the `metanorma` CTAN package) is installed correctly, this flag cannot be omitted, but it can be simplified leveraging TeX's path resolver by writing `--stylesheet=$(kpsewhich metanorma.xsl)`

All that said, the piece of pipeline which is missing from MN
* is `TEX -> ADOC`
* is equivalent to the combination of the two commands above
* requires the presence of `latexml` and `latexmlpost` (pretty common in LaTeX distributions)
* requires the presence of `tex2mn` (i.e. the `metanorma` CTAN package) either properly installed or put in a known folder

**CAVEAT:** we need an unreleased feature of `latexml`, contained precisely in `git://github.com/brucemiller/LaTeXML.git@9a0e7dc5`
Installation details for common OSs are available in the workflows: https://github.com/metanorma/tex2mn/tree/master/.github/workflows
We'll have to wait for LaTeXML 0.8.5 to avoid handpicking a commit -- it's expected by July 2020: https://github.com/brucemiller/LaTeXML/issues/1234#issuecomment-591046589 Here is the progress status: https://github.com/brucemiller/LaTeXML/milestone/12

**Comment by ronaldtse** [comment]
@paolobrasolin thank you for this great news!

Could you help with:

1. Provide setup instructions regarding CTAN and the metanorma.xsl stylesheet
2. Update https://github.com/metanorma/mn-samples-tex-iso to reflect changes (and update its code to the latest mn-samples-iso)
3. Update https://github.com/metanorma/rfc-camelot-holy-grenade-tex to make sure it is compilable 
4. Explain to @opoudjis  on how to provide "TEX -> ADOC" flow inside the Metanorma gems (e.g. metanorma-tex gem or tex2mn gem?)


For the handpicked LaTeXML, @CAMOBAP can you help release that version in Snap as "edge" for now? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse @paolobrasolin we already did --edge release for snap for git://github.com/brucemiller/LaTeXML.git@9a0e7dc5

<img width="1106" alt="Screen Shot 2020-05-04 at 3 48 06 PM" src="https://user-images.githubusercontent.com/2169738/80967271-bd0b0300-8e1e-11ea-9825-9241ff021893.png">

Please let me know if we should do the same for chocolatey

P.S. for OSX we don't control brew package, but it can be easily installed like this https://github.com/metanorma/metanorma-standoc/blob/master/.github/workflows/macos.yml#L30-L32

**Comment by CAMOBAP** [comment]
ping @ronaldtse @paolobrasolin

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Yes, can you please do the same for chocolatey, and can you also write up some documentation on metanorma.com on how to install this special version of LaTeXML for Metanorma on different platforms?

**Comment by CAMOBAP** [comment]
@ronaldtse done https://github.com/metanorma/metanorma.com/pull/263

**Comment by CAMOBAP** [comment]
Done
